import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://automationexercise.com/');
  await page.getByRole('link', { name: ' Signup / Login' }).click();
  await page.getByRole('textbox', { name: 'Name' }).click();
  await page.getByRole('textbox', { name: 'Name' }).fill('avi');
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').click();
  await page.locator('form').filter({ hasText: 'Signup' }).getByPlaceholder('Email Address').fill('avinash@sharma.com');
  await page.getByRole('button', { name: 'Signup' }).click();
  await page.locator('#uniform-id_gender1').click();
  await page.getByRole('textbox', { name: 'Password *' }).click();
  await page.getByRole('textbox', { name: 'Password *' }).fill('Test@1234');
  await expect(page.locator('#form')).toContainText('Address Information');
  await page.getByRole('textbox', { name: 'First name *' }).click();
  await page.getByRole('textbox', { name: 'First name *' }).fill('avi');
  await page.getByRole('textbox', { name: 'First name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Last name *' }).fill('sharma');
  await page.getByRole('textbox', { name: 'Last name *' }).press('Tab');
  await page.getByRole('textbox', { name: 'Company', exact: true }).press('Tab');
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).fill('Bhopal');
  await page.getByRole('textbox', { name: 'Address * (Street address, P.' }).press('Tab');
  await page.getByRole('textbox', { name: 'Address 2' }).press('Tab');
  await page.getByLabel('Country *').press('Tab');
  await page.getByRole('textbox', { name: 'State *' }).fill('MP');
  await page.getByRole('textbox', { name: 'State *' }).press('Tab');
  await page.getByRole('textbox', { name: 'City * Zipcode *' }).fill('Bhopal');
  await page.locator('#zipcode').click();
  await page.locator('#zipcode').fill('998122');
  await page.getByRole('textbox', { name: 'Mobile Number *' }).click();
  await page.getByRole('textbox', { name: 'Mobile Number *' }).fill('1234567890');
  await page.getByRole('button', { name: 'Create Account' }).click();
  await page.getByText('Account Created!').click();
  await expect(page.locator('b')).toContainText('Account Created!');
  await page.getByRole('link', { name: 'Continue' }).click();
  await expect(page.locator('#header')).toContainText('Delete Account');
  await page.getByRole('link', { name: ' Delete Account' }).click();
  await expect(page.locator('b')).toContainText('Account Deleted!');
  await page.getByRole('link', { name: 'Continue' }).click();
});